### PR TITLE
Fix #2209 layout changes issue

### LINKED ISSUE #2209: ContainerFragment in EditImageActivity changes it's layout on orientation change
**Actual Behaviour**

On selecting sub component of in container fragment and then changing the orientation change the layout.

**Expected Behaviour**

layout should not be changed.

**Steps to reproduce it**

Step 1. Click on edit image button and click any of option like enhance option

Step 2. click on contrast then it shows a progress bar

Step 3 Change the orientation of the phone, layout changes.

**Screenshots of the issue**

whatsapp image 2018-10-05 at 11 56 35 pm

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by sparrow007**
Fixed #2209 

Changes: there is two initial value for middle and bottom fragment which is temporary and after initialization all the fragment changes done by default flow (using mode).

Screenshots of the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java [hunk 1]
```diff
@@ -367,12 +371,14 @@ public void setEffectType(int type, int mode){
...
      */
     public void changeMiddleFragment(int index){
+            initalMiddleFragment = index;
             getSupportFragmentManager()
                     .beginTransaction()
                     .replace(R.id.preview_container, getFragment(index))
                     .commit();
     }
 
+
```
Comment (GOVINDDIXIT) [inline app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java]: remove extra line, rest looks good

Comment (sparrow007) [reply app/src/main/java/org/fossasia/phimpme/editor/EditImageActivity.java]: ok got it.

**Comment by abishekvashok** [comment]
Thank you.
