### PR TITLE
Fixes #190 Flash fires according to image resource

### LINKED ISSUE #190: Flash not firing at start of the App.
**Actual Behaviour**

At the first launch of the application, the flash not firing in accordance with the image resource.

**Expected Behaviour**

The flash should fire in accordance with the image resource.

**Steps to reproduce it**

Open app, go to camera, click picture, flash won't fire.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by anantprsd5**
Fixes issue #190 Flash not firing at first launch.

### CODE REVIEW

File: app/src/main/java/vn/mbm/phimp/me/Camera2.java [hunk 1]
```diff
@@ -799,6 +798,7 @@ public void surfaceChanged(SurfaceHolder holder, int format, int w, int h) {
 		// the preview.
 		Log.e("Surface","Change");
 		Camera.Parameters parameters = mCamera.getParameters();
+        parameters.setFlashMode(Camera.Parameters.FLASH_MODE_ON);
```
Comment (Abhi2424shek) [inline app/src/main/java/vn/mbm/phimp/me/Camera2.java]: Properly intend itm

**Comment by anantprsd5** [comment]
@Abhi2424shek Done. Thanks.

**Comment by anantprsd5** [comment]
@pa1pal @Abhi2424shek Please review.
