### PR TITLE
Replaced DescriptionActivity with Themed Dialog box

### LINKED ISSUE #702: Replacement of Description activity with Dialog box
**Actual Behaviour**

Currently we have description activity to store the info of the picture.

**Expected Behaviour**

We should use dialog boxes instead of Description activity as it is not required for just writing the info and it can be dealt with using a dialog box.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Would you like to work on the issue?**

Yes.

@mohitmanuja @pa1pal @vinaysajjanapu @Subhankar29 Need suggestion on this.

### PR DESCRIPTION
**Pull request by anantprsd5**
Fix #702 

Changes: Replaced description activity with a dialog box

Screen shots for the change:

photo6267272353872455603

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -594,6 +627,31 @@ public void folderSelected(String path) {
...
+        editxtDescription.setTextColor(activity.getTextColor());
+
+        realm = Realm.getDefaultInstance();
+        databaseHelper =new DatabaseHelper(realm);
+        temp= databaseHelper.getImageDesc(pathForDescription);
+        if(temp != null) {
+            editxtDescription.setText(temp.getTitle());
+        }
+        else
+            editxtDescription.setHint(getString(R.string.description_hint));
```
Comment (pa1pal) [inline app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java]: is `hint` causing the cursor to not in center
image

Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/leafpic/activities/SingleMediaActivity.java]: @pa1pal Done. Please check again.
