### PR TITLE
fix #2463: multiple snackbar issue fixed.

### LINKED ISSUE #2463: multiple snackbar issue
**Actual Behaviour**

redundant snackbar in accounts activity.
snackbar is not displayed when the user is sharing an image personally on imgur and he is not signed in.

**Expected Behaviour**

redundant snackbar should be removed.
toast should be displayed instead of snackbar.

**Steps to reproduce it**

share a image via imgur when not signed in. tap on personal. no message is displayed, asking the user to sign in first.

**Would you like to work on the issue?**

yes.

### PR DESCRIPTION
**Pull request by kk63852**
Fixed #2463 

Changes: 
redundant snackbar from accounts activity removed.
snackbar of shareToImgur replaced with a toast.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java [hunk 1]
```diff
@@ -308,9 +308,7 @@ public void onClick(View view) {
                 /*case ONEDRIVE:
                     signInOneDrive();
                     break;*/
-
-                default:
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/accounts/AccountActivity.java]: Please don't leave an empty default

**Comment by abishekvashok** [comment]
Thanks
