### PR TITLE
Fix #2361 customize viewer issue fixed.

### LINKED ISSUE #2361: customize viewer issue.
**Actual Behaviour**

transparency grade feature stays enabled when the switch button is disabled.

**Expected Behaviour**

the grade should be disabled when the switch button is disabled.

**Steps to reproduce it**

go to settings and navigate to customize viewer. disable the switch button . the transparency grade stays enabled.

**Screenshots of the issue**

whatsapp image 2019-01-02 at 18 15 07 1
whatsapp image 2019-01-02 at 18 15 07

**Would you like to work on the issue?**

yes.

### PR DESCRIPTION
**Pull request by angmas1**
Fixed #2361 

Changes: SettingsActivity.java, dialog_media_viewer_theme.xml. Grade disabled when switch is unchecked and enabled when switch is checked.

Screenshots of the change: 
image

image

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java [hunk 1]
```diff
@@ -379,7 +381,7 @@ public void onStartTrackingTouch(SeekBar seekBar) {
             }
             @Override
             public void onStopTrackingTouch(SeekBar seekBar) {
-                
+
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java]: Please remove this extra space.

Comment (angmas1) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java]: ok

**Comment by angmas1** [comment]
@abishekvashok please review
