### PR TITLE
Fixed login prompt for box storage from Share activity

### LINKED ISSUE #882: Sharing image to box sometimes prompts to login from account manager
**Actual Behaviour**

Sharing image to box prompts to login from account manager in spite of being signed in

**Expected Behaviour**

It should prompt only if not signed in from account manager.

**Steps to reproduce it**

1. Open account manager.
2. Sign in.
3. Close the app.
4. Open sharingActivity.
5. Share image to box.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by anantprsd5**
Fix #882 

Changes: Changed the last authenticated check with Realm results

1. Login to box.
2. Close the application.
3. Open ShareActivity and share image to box now works fine.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java [hunk 1]
```diff
@@ -382,12 +391,14 @@ public void onItemLongPress(View childView, int position) {
     }
 
     private void boxShare() {
-        try {
-            sessionBox = new BoxSession(SharingActivity.this);
-            if (BoxAuthentication.getInstance().getLastAuthenticatedUserId(SharingActivity.this) != null)
-                new UploadToBox().execute();
-            else SnackBarHandler.show(parent, R.string.login_box);
-        } catch (RuntimeException e) {
+        RealmQuery<AccountDatabase> query = realm.where(AccountDatabase.class);
```
Comment (mohitmanuja) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: use Utils.checkIfalreadyExist() function instead of this.

Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: @mohitmanuja Done.
