### PR TITLE
Checking if Instagram is installed or not and handling No internet connection error

### LINKED ISSUE #635: Check if Instagram is installed or not
**Actual Behaviour**

If Instagram is not installed then a white screen appears showing error message "No app is installed to complete the action"

**Expected Behaviour**
Display snackBar to display the message. 

**Steps to reproduce it**
ShareActivity->Instagram upload button

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by Subhankar29**
Fix #635 and #664  

Changes: Display snackBar to display the message if Instagram is not installed. Display Snackbar if internet connection is not available.

- Check if Instagram is installed or not.

- Check if internet connection is available or not.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/SharingActivity.java [hunk 1]
```diff
@@ -272,15 +273,30 @@ private void otherShare() {
...
+            share.putExtra(Intent.EXTRA_STREAM, uri);
+            share.setType("image/*");
+            share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
+            startActivity(Intent.createChooser(share, caption));
+            atleastOneShare = true;
+        }else
+            Snackbar.make(parent,R.string.instagram_not_installed,Snackbar.LENGTH_LONG).show();
+    }
+
+    private boolean isAppInstalled(String packageName) {
```
Comment (pa1pal) [inline app/src/main/java/org/fossasia/phimpme/SharingActivity.java]: Move this function in `Utils` class, because its generic and if we require  to use this in future, Don't need to create again.

Comment (Subhankar29) [inline app/src/main/java/org/fossasia/phimpme/SharingActivity.java]: Sure will do that.
