### PR TITLE
fix: App is not opening after denied permission

### LINKED ISSUE #2218: App is not opening after denied permission
**Actual Behaviour**

The application is freeze when the user denied the file storage permission.

**Expected Behaviour**

Tell the user that why the permission is important and ask again for permission.

**Steps to reproduce it**

Show not cancellable alert dialog when the user denied the permission and after click okay, ask again for the permission.

**Would you like to work on the issue?**

Yes, I want to work on this issue.

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixed #2218 

Changes: 

- SplashScreen.java
- ic_caution.xml (New)
- strings.xml

Screenshots of the change: 

<p align="center">
 
</p>

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SplashScreen.java [hunk 1]
```diff
@@ -148,14 +154,31 @@ public void onRequestPermissionsResult(int requestCode, @NonNull String[] permis
...
+                }
                 break;
             default:
                 super.onRequestPermissionsResult(requestCode, permissions, grantResults);
         }
     }
 
+    private void showPermissionAlertDialog() {
+        AlertDialog.Builder builder = new AlertDialog.Builder(this);
+        builder.setIcon(R.drawable.ic_caution);
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SplashScreen.java]: Set a white tint for the icon maybe.

File: app/src/main/res/drawable/ic_caution.xml [hunk 2]
```diff
@@ -0,0 +1,16 @@
+<?xml version="1.0" encoding="utf-8"?>
+<vector xmlns:android="http://schemas.android.com/apk/res/android"
+    android:width="361.117dp"
```
Comment (abishekvashok) [inline app/src/main/res/drawable/ic_caution.xml]: It should not be like this, as primary and secondary colours can change. Instead of hardcoding white colour, implement a `tint`

Comment (liveHarshit) [reply app/src/main/res/drawable/ic_caution.xml]: Updated.

Comment (abishekvashok) [reply app/src/main/res/drawable/ic_caution.xml]: Where?

Comment (liveHarshit) [reply app/src/main/res/drawable/ic_caution.xml]: After that
```
android:height="361.117dp"
    android:viewportWidth="361.117"
    android:viewportHeight="361.117"
    android:tint="@color/white">
```

Comment (abishekvashok) [reply app/src/main/res/drawable/ic_caution.xml]: It should be the secondary color, and not white

Comment (liveHarshit) [reply app/src/main/res/drawable/ic_caution.xml]: @abishekvashok 
Should I change it like that, same color in tint and fill color?
``` xml
<vector
    android:tint="#ffffff">
    <path
        android:fillColor="#ffffff"
        />
    <path
        android:fillColor="#ffffff"
         />
    <path
        android:fillColor="#ffffff"
         />
</vector>
```

Comment (abishekvashok) [reply app/src/main/res/drawable/ic_caution.xml]: Please use a color matching with a secondary color.

Comment (liveHarshit) [reply app/src/main/res/drawable/ic_caution.xml]: Updated
