### PR TITLE
Fix #2180 (Favorite button color is not changed after adding it to the favorite list)

### LINKED ISSUE #2180: Favorite button color is not changed after adding it to the favorite list.
**Actual Behaviour**

Select the first image of any album and tap on favorite button it changes it's color for indicating that it has been added to favorite list but when reopen the app and go to same first image of the album color is not changing.

**Expected Behaviour**

Selected image favorite button should changes it's color for indicating that it has been added to favorite list.

**Steps to reproduce it**

Step 1: select the first image from any album

Step 2: click on the favorite button(color of button will changed)

Step 3: start the app again and go to same image and color will not changed which indicate that this image is not in favorite section.but it does.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sparrow007**
Fixed #2180 

Changes: [when clicking on the first image of the album it's not calling the OnPageChangeListener that's why it's button not getting updated so i added below code to change it's color when it's in the favorite list.]

GIF of the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -385,6 +393,13 @@ public void onPageChanged(int oldPosition, int position) {
             adapter = new ImageAdapter(LFMainActivity.listAll, basicCallBack, this, this);
             getSupportActionBar().setTitle(all_photo_pos + 1 + " " + getString(R.string.of) + " " + size_all);
             current_image_pos = all_photo_pos;
+            if (bottomMenu.findItem(R.id.action_favourites).getIcon() == null) {
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Are you sure of using this logic? Shouldnt be `.getColorFilter()`?

Comment (sparrow007) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: getIcon() is returning the Drawable object so if drawable is null there should not any chance that getColorFilter() gets called , it will throw a NullPointerException to invoke a method on null object.

**Comment by abishekvashok** [comment]
Thank you!

**Comment by sparrow007** [comment]
No thank you , you guy's are awesome.

**Comment by abishekvashok** [comment]
(^^)
