### PR TITLE
fix: A photo cannot be renamed with the same name.

### LINKED ISSUE #2610: Renaming an image with the same name gives no notification.
**Describe the bug**
While renaming an image, if the image is renamed with the same name, the image is still being renamed.

**To Reproduce**
Try to rename an image with the same name as it has. No notification is given.

**Expected behavior**
The image should not be renamed and a snack bar should be shown saying that there was no change in the name of the image.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 PLus|
|Android Version|Android 9   |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2610 

Changes: Now a photo cannot be renamed if the user renames with the same name.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -1281,28 +1281,33 @@ public void onClick(DialogInterface dialogInterface, int i) {
                                 alertDialog.show();
                                 AlertDialogsHelper.setButtonTextColor(new int[]{DialogInterface.BUTTON_POSITIVE, DialogInterface.BUTTON_NEGATIVE, DialogInterface.BUTTON_NEUTRAL}, getAccentColor(), alertDialog);
                             } else {
-                                int index = file.getPath().lastIndexOf("/");
-                                String path = file.getPath().substring(0, index);
```
Comment (kk63852) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: why were these lines removed only to be added later?

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: I used an additional if condition. So all the lines have been shifted down. It's just appearing to be this way here. I have just added lines, not deleted any.

Comment (kk63852) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: cool.
