### PR TITLE
Fix #1167 -Highlight the sub-edit option when selected.

### LINKED ISSUE #1167: Highlight edit sub-option just like the edit option
**Actual Behaviour**

The edit sub-option like HUE in the screenshot is not highlighted when it is selected.

**Expected Behaviour**

It should be highlighted

**Steps to reproduce it**

Go to edit any photo and select any effect to add.

**Screenshots of the issue**

21298069_1806911089337697_5885298401859338240_n

**Would you like to work on the issue?**

Yes
@mohitmanuja @vinaysajjanapu Should this be there?

### PR DESCRIPTION
**Pull request by mayank8318**
Fix #1167 

Changes: Highlight the effect under consideration.

Screenshots for the change: 
18946638_1812062235489249_2006984994186067968_n

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java [hunk 1]
```diff
@@ -205,15 +219,35 @@ public void onBindViewHolder(mRecyclerAdapter.mViewHolder holder, final int posi
...
                     itemClicked(position,v);
                 }
             });
         }
 
+        private void highlightSelectedOption(int position, View v) {
+            currentSelection = position;
+            int color = ContextCompat.getColor(v.getContext(), R.color.md_grey_200);
+            int length = titlelist.length();
+            for(int i = 0;i < length;i++)
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/editor/fragment/RecyclerMenuFragment.java]: Why is for loop used here? It can be done using the position passed in as the parameter.

**Comment by mayank8318** [comment]
@anantprsd5 Actually I was using it to set all the background to Color.TRANSPARENT earlier when I was not storing the currentSelection position.
But now that loop is not required as I already have the index of the last active option.
Thanks :)
