### PR TITLE
fix: Added a background dialog for delete, copy/move actions

### LINKED ISSUE #2455: progress dialog for many functions like delete, copy.
**Actual Behaviour**

while trying to move or delete large number of files(in multiples of tens) only refreshing is enabled. 

**Expected Behaviour**

there should be a progress dialog to inform the user about the progress of the task being done.

**Steps to reproduce it**

open a album and delete large number of files. refreshing is enabled only.

**Would you like to work on the issue?**

yes.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2455

Changes: Added a background progress dialog for copy/move and delete actions.

Screenshots of the change: 

screencap

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic @iamareebjamal @abishekvashok @mariobehling  please review.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -2042,13 +2044,23 @@ public void onClick(DialogInterface dialog, int which) {
...
           @Override
           protected void onPreExecute() {
+            dialog = getLoadingDialog(context, "Deleting", false);
+            dialog.show();
             swipeRefreshLayout.setRefreshing(true);
             super.onPreExecute();
           }
 
+          private Dialog getLoadingDialog(Context context, String title, boolean canCancel) {
+            ProgressDialog dialog = new ProgressDialog(context);
```
Comment (adityastic) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: ProgressDialog was depreciated in api 26 as i remember. Use progress bar instead

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Is it necessary? ProgressDialog is still working.

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Deprecated doesn't mean disabled

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @iamareebjamal I know. I think that we shouldn't shift to Progress bar because everywhere we are using ProgressDialog. If we shift this to progress bar, we should shift others too to progress bars.

Comment (adityastic) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: > A program element annotated @Deprecated is one that programmers are discouraged from using, typically because it is dangerous, or because a better alternative exists.


It's upto you, but it is suggested as it is more robust to api changes

Comment (iamareebjamal) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Yeah, not everytime you can have a UI component which lets user dismiss it. See the stackoverflow thread that not everyone is happy with this change,

**Comment by yashk2000** [comment]
@abishekvashok is that really needed? This dialog pops for a very brief amount of time, mostly just a second. The only time you can actually see it properly is while copying photos, that too for just a second or so. 
Do we need to make a progress bar notification for such a short period? The user won't even see it.

**Comment by yashk2000** [comment]
> @abishekvashok is that really needed? This dialog pops for a very brief amount of time, mostly just a second. The only time you can actually see it properly is while copying photos, that too for just a second or so.
> Do we need to make a progress bar notification for such a short period? The user won't even see it.

@abishekvashok what do you think?

**Comment by abishekvashok** [comment]
> @abishekvashok is that really needed? This dialog pops for a very brief amount of time, mostly just a second. The only time you can actually see it properly is while copying photos, that too for just a second or so.
Do we need to make a progress bar notification for such a short period? The user won't even see it.

@yashk2000 it can serve as for further actions in the future, so I guess it would be a better investment on our part. Let's do it the correct way instead of the easy way

**Comment by yashk2000** [comment]
@abishekvashok I was not doing the easy thing, just following the current convention in the app.
I still did not get the purpose of using the notification method though. I have tested the places where this progress dialog pops up, and everywhere, it comes for a very small period of time, and most often, it isn't even visible. 
Could you please tell me the need for the notification progress bar in such cases where it won't even be visible?

**Comment by abishekvashok** [comment]
> I still did not get the purpose of using the notification method though. I have tested the places where this progress dialog pops up, and everywhere, it comes for a very small period of time, and most often, it isn't even visible.

It's about providing a better UX, a better standard.

**Comment by yashk2000** [comment]
@abishekvashok ok. I'll make a notification dialog bar for these changes.

**Comment by yashk2000** [comment]
@abishekvashok @iamareebjamal I tried a few methods to display the notification progress bar. The app built successfully, but when I run the app, and the copy operation, I am unable to see the notification progress bar.

**Comment by iamareebjamal** [comment]
I don't know if we can invest that much time in notification updates. This is not that long a process. Also, we are not handling progress updates and the ability to cancel tasks, for which notification status are used. Without these capabilities, notifications are as useful as a progress dialog. Once we are that much stable and can handle canceling and progress, we can show notifications. Also, AFAIK, we have yet to handle what would happen if a user opens a file that has since been deleted or copied as the notification status does not block the UI.

YAGNI - You ain't gonna need it

Think twice before adding a feature, not just because you think you're going to need it

Either we have to handle everything before adding this feature. Which will delay this PR by a week at least, or we do a simple thing and move to other more important bugs and features and come back when we have that much time and effort on us to invest in this requirement

**Comment by yashk2000** [comment]
@iamareebjamal so I shouldn't implement that feature right now. I guess then the progress dialogs being shown right now are good enough. If it's fine, can this pr be merged then?
