### PR TITLE
 Fix: #1184 - Zoom, improved UX

### LINKED ISSUE #1184: Zoom functionality is not working
**Actual Behaviour**
Earlier on double clicking zoom was working but now it is not working

**Expected Behaviour**
The image should be able to zoom in/out on double-clicking it.

**Steps to reproduce it**
Just open up an image and double click it to zoom

**Screenshots of the issue**

giphy

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by aditya98ak**
Fix #1184 

Changes: Earlier zoom was not working, if the user clicks on an image, only toolbars were disappearing, now all is working fine.

Screenshots for the change: 
giphy

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -408,15 +410,15 @@ protected void onActivityResult(int requestCode, int resultCode, Intent data) {
...
         boolean isImageEdit = data.getBooleanExtra(EditImageActivity.IMAGE_IS_EDIT, false);
 
-        if (isImageEdit){
+        if (isImageEdit) {
 
-        }else{//Or use the original unedited pictures
-            newFilePath = data.getStringExtra(EditImageActivity.FILE_PATH);;
+        } else {//Or use the original unedited pictures
+            newFilePath = data.getStringExtra(EditImageActivity.FILE_PATH);
+            ;
```
Comment (the-dagger) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Why is an extra semicolon placed here?
Also, try not to refactor code until and unless it is absolutely required.

Comment (aditya98ak) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: I apologise : (
Will take care next time.

**Comment by aditya98ak** [comment]
@the-dagger Please review
