### PR TITLE
#1735 Fixed-Whatsapp sharing error

### LINKED ISSUE #1735: While sharing image in whatsapp and instagram its not adding in upload history
Actual Behaviour
The images is not being loaded in upload history after sharing in instagram and whatsapp.

Expected Behaviour
The images is to be loaded in upload history after sharing in instagram and whatsapp.

Steps to reproduce it

Share any image in whatsapp and instagram it doesn't show in uploadhistory

### PR DESCRIPTION
**Pull request by Ananthusubramanian**
Fixed #1735:Whatsapp shared items not showing in upload history

Changes:Edited Sharingactivity , did by sending value from whatsappsharing function

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java [hunk 1]
```diff
@@ -1035,6 +1037,8 @@ private void shareToWhatsapp() {
         share.setType("image/*");
         share.putExtra(Intent.EXTRA_TEXT, caption);
         startActivityForResult(Intent.createChooser(share, context.getString(R.string.whatsapp)), SHARE_WHATSAPP);
+        triedUploading=true;
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: Add a space btw. = (Before and after at all instances)

**Comment by Ananthusubramanian** [comment]
@abishekvashok  I did the changes in declaration
