### PR TITLE
Fix #912 - Set color of tab icon bottom navigation view

### LINKED ISSUE #912: Background Color of Tab Icon Should Adjust According to Primary Colour
**Actual Behaviour**

The background colour for highlighting the current tab is fixed. So if the primary colour is same as the highlight colour the tab icon becomes invisible. 

**Expected Behaviour**
The background colour of the icon should adjust according to primary colour. 

**Steps to reproduce it**
Switch primary colour to dark grey
**Screenshots of the issue**
image

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fix #912 

Screenshots for the change: 
image
image

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java [hunk 1]
```diff
@@ -18,11 +20,25 @@
...
+    private int[] colors = new int[] {
+            Color.WHITE, // checked
+            0 // unchecked set default in onCreate
+    };
+
     @Override
     protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         setContentView(getContentViewId());
+        colors[1] = getResources().getColor(R.color.bottom_navigation_tabs , getTheme());
```
Comment (vinaysajjanapu) [inline app/src/main/java/org/fossasia/phimpme/base/BaseActivity.java]: try using this once
    colors[1]  = ContextCompat.getColor(this, R.color.bottom_navigation_tabs);
