### PR TITLE
After resetting password forgot password dialog is dismissed.

### LINKED ISSUE #2392: Forgot password dialog issue.
**Actual Behaviour**

When the user resets the password by pressing forgot password, after password reset, the user should directly be shown the insert password screen. But instead, the forgot password dialog appears again which has to be canceled to proceed to the insert password screen.

**Expected Behaviour**

The user should directly be shown the insert password screen.

**Steps to reproduce it**

1) Go to security settings to set a password if not set already.
2) Press fo forgot password when entering the password again.
3) After resetting the password, forgot password dialog is still open which has to be canceled to proceed to the inset password screen.

**GIF of the issue**

ezgif com-video-to-gif 1

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2392 

Changes: After resetting the password, the user is directly shown the insert password screen instead of the forgot password dialog screen.

GIF of the change: 
ezgif com-video-to-gif 2

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java [hunk 1]
```diff
@@ -202,6 +202,7 @@ public void onClick(View view) {
                         String answer1 = "";
                         answer1 = SP.getString("Security Answer", answer1);
                         if (Objects.equals(answer1, securityAnswer1.getText().toString())) {
+                            dialog.dismiss();
                             changePassword(activity, passwordDialog);
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java]: Move this above

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java]: @abishekvashok can you please tell me what do I have to move above? I did not understand what is to be moved.

Comment (abishekvashok) [reply app/src/main/java/org/fossasia/phimpme/gallery/util/SecurityHelper.java]: Dismiss the dialog only after the changepassword function is called.

**Comment by yashk2000** [comment]
@abishekvashok I made the changes.

**Comment by abishekvashok** [comment]
Thanks
