### PR TITLE
Fix #2525 Back button get stuck when there is deny of permission

### LINKED ISSUE #2525: Back button get stuck when there is deny of permission
**Actual Behaviour**

Back button is not working when deny the camera permission (click on Never ask again).

**Expected Behaviour**

Back button should work.

**Steps to reproduce it**

Step 1. App open first time.

Step 2. Click on camera tab it will ask for permission

Step 3. Deny the permission and also click on never ask again after that back button is not working,

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sparrow007**
Fixed #2525 

Changes: [calling the runtime permission in onResume can create a infinite loop if user deny the permission so i check that if user deny permission temporary or permanent and return if permanent deny the permission.]

GIF of the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java [hunk 1]
```diff
@@ -2855,6 +2860,13 @@ public void onRequestPermissionsResult(int requestCode, @NonNull String permissi
                         Log.d(TAG, "camera permission granted");
                     preview.retryOpenCamera();
                 } else {
+                    if (ActivityCompat.shouldShowRequestPermissionRationale(CameraActivity.this,
+                            Manifest.permission.CAMERA)) {
+                        // now, user has denied permission (but not permanently!)
+
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java]: Please remove this extra line.

File: app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java [hunk 2]
```diff
@@ -2855,6 +2860,13 @@ public void onRequestPermissionsResult(int requestCode, @NonNull String permissi
...
+                    } else {
+                        permanentDenyPermission = true;
+                    }
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java]: There is no need to add braces here, it is a single statement. Just type it in front of `else`.

Comment (sparrow007) [reply app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java]: i got another idea , will push in a minute.
