### PR TITLE
Photos item view modified

### LINKED ISSUE #1990: Photos item view modification.
**Actual Behaviour**

Currently, a yellow colored star mark appears on the photo item view of the photos added to favorites, due to which the UI doesn't look good.

**Expected Behaviour**

Star mark should not appear in the photo item view, instead the heart icon in the SingleMedia Activity should be color marked accordingly for adding/removing photos from favourites.

**Steps to reproduce it**

Add photo/photos to favorites and view those photos in the album view(i.e through LFMainActivity).

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
Fixed #1990 
Changes: Yellow colored star mark no longer appears in the photos item view for fav marked photos, the heart icon in the SingleMediaActivity appears color marked(Accent color) for the photos added to the fav collection.
gif before change:
videotogif_2018 05 22_02 13 23

gif after change:
videotogif_2018 05 22_02 20 10

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@anantprsd5 @iamareebjamal @the-dagger @Subhankar29 @vanhonit Please review.

**Comment by mariobehling** [comment]
Please provide a screenshot.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -530,16 +533,30 @@ public void onConfigurationChanged(Configuration newConfig) {
...
+        
         if(allPhotoMode || favphotomode){
             menu.findItem(R.id.action_cover).setVisible(false);
         }
         if (!allPhotoMode && !favphotomode && !upoadhis){
             menu.setGroupVisible(R.id.only_photos_options, true);
         }
         else if(!allPhotoMode && favphotomode && !upoadhis){
-            menu.findItem(R.id.action_favourites).setVisible(false);
+            menu.findItem(R.id.action_favourites2).setVisible(false);
```
Comment (mayank8318) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Why is this called `action_favourite2` and not `action_favourite`?

File: app/src/main/res/menu/menu_bottom_view_pager.xml [hunk 2]
```diff
@@ -30,7 +30,7 @@
         android:title="@string/details"/>
 
     <item
-        android:id="@+id/action_favourites"
+        android:id="@+id/action_favourites2"
```
Comment (mayank8318) [inline app/src/main/res/menu/menu_bottom_view_pager.xml]: Why is this called `action_favourite2` and not `action_favourite`?

Comment (sauravvishal8797) [reply app/src/main/res/menu/menu_bottom_view_pager.xml]: As we have two favorite menu items, one for the LFMainActivity and one for the SingleMediaActivity while testing had changed the name to avoid confusion, but forgot to change it back to action_favourites. Will revert it to action_favourites now.
