### PR TITLE
Fix #1251 soft keyboard now pops up automatically 

### LINKED ISSUE #1251: Soft keyboard doesn't pop up automatically in create new folder dialog
**Actual Behaviour**

Currently when we click on create new folder soft keyboard doesn't pop up automatically.

**Expected Behaviour**

Soft keyboard should automatically pop up when we click on create new folder

**Steps to reproduce it**

Click on any photo. select move or copy. Then click on create new folder

**Screenshots of the issue**
screenshot_20171001-192759

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fix #1251 

Changes: soft keyboard now pops up automatically in create new folder dialog

Screenshots for the change: 
screenshot_20171002-000707

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java [hunk 1]
```diff
@@ -122,6 +124,8 @@ public void onClick(View view) {
 	  @Override
 	  public void onClick(View view) {
 		final EditText editText = new EditText(getContext());
+          InputMethodManager inputMethodManager = (InputMethodManager)getActivity().getSystemService(Context.INPUT_METHOD_SERVICE);
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java]: @nikit19 Please indent the code properly

**Comment by nikit19** [comment]
@anantprsd5  changes done
