### PR TITLE
Fixes #1222 Bottom navbar hides when albums or photos are selected

### LINKED ISSUE #1222: BottomNavigationView should be hidden when albums/photos are selected
**Actual Behaviour**

Currently when the albums or photos are long pressed they get selected but the BottomNavigationView is still visible.

**Expected Behaviour**

BottomNavigationView is not required when the user has selected albums or photos. It should be hidden as long as the user is selecting folders and then again become visible when the user has come out of the editmode.

**Steps to reproduce it**

open the app and long press any album or photo

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fix #1222 

Changes: BottomNavigationBar is hidden when the user selects albums or photos and becomes again visible when the user presses the back button ,deselects all the selected media or clicks on any menu item.

Screenshots for the change: 

ezgif com-video-to-gif 7

### CODE REVIEW

**Comment by nikit19** [comment]
@anantprsd5 @mohitmanuja  @vinaysajjanapu please review.
thank you

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -169,6 +171,11 @@ private int toggleSelectPhoto(Media m) {
                 selectedMedias.remove(m);
         }
         if (selectedMedias.size() == 0) {
+            if(editMode && hidenav )
+            {
+                getNavigationBar();
+                hidenav=false;
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Put this line in the getNavigationBar function

**Comment by nikit19** [comment]
@anantprsd5  is it fine now?
