### PR TITLE
Fixes #273 No confirmation on back button pressed in edit image page

### LINKED ISSUE #273: No confirmation on back button pressed in edit image page
**Actual Behaviour**

The activity just closes when back button is pressed in edit image page (CropImage activity). This may cause loss of edited image when back button got pressed accidentally.

**Expected Behaviour**

Should display a dialog asking a confirmation from the user to close the activi

**Steps to reproduce it**

Select image in gallery page. Press edit FAB. Perform some edits. Press back button.

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fixes issue #273 

Changes: Added alert dialog for confirmation.

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @vinaysajjanapu we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/vinaysajjanapu/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: app/src/main/java/vn/mbm/phimp/me/image/CropImage.java [hunk 1]
```diff
@@ -120,6 +122,24 @@
 	static Context ctx;
 	static String p[] = null;
     private String newpath;
+
+    @Override
+    public void onBackPressed() {
```
Comment (pa1pal) [inline app/src/main/java/vn/mbm/phimp/me/image/CropImage.java]: put the function below in the file. Although it won't make any difference but it should be below in hierarchy.

File: app/src/main/java/vn/mbm/phimp/me/image/CropImage.java [hunk 2]
```diff
@@ -105,7 +107,7 @@
     HighlightView mCrop;
```
Comment (pa1pal) [inline app/src/main/java/vn/mbm/phimp/me/image/CropImage.java]: Please fix the indentation of the file.
