### PR TITLE
Pinterest Database insertion and Notification handler

### LINKED ISSUE #779: Pinterest Database insertion of logged in User
**Actual Behaviour**

Currently, the username is not displayed after logging into Pinterest.   
**Expected Behaviour**

Display the username of the logged in user on AccountActivity

**Steps to reproduce it**

AccountActivity->Pinterest

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by Subhankar29**
Fix #779 
Changes:

- [x] Removed inappropriate message on database insertion in Pinterest. 
- [x] Proper Database Insertion of Logged In user.
- [x] Show notification to upload image

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java [hunk 1]
```diff
@@ -633,18 +633,21 @@ public void onClick(View v) {
     }
 
     private void shareToPinterest(final String boardID) {
+        NotificationHandler.make();
```
Comment (mohitmanuja) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: Also, add snackbar here that upload is in progress.
