### PR TITLE
Fix #1129 - Home button is now working as expected

### LINKED ISSUE #1129: Home button is not working when user open up any album
**Actual Behaviour**

The home button is not doing anything when the user has selected any album and bottom navigation bar is still visible.

**Expected Behaviour**

Clicking on the home button should take the user to the home screen i.e, LFMainActivity.
**Steps to reproduce it**

Just open up the app, go to any album, click on the home button, Nothing will happen!

**Screenshots of the issue**
giphy

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by aditya98ak**
Fix #1129 Home button is now working as expected!

**Screenshots for the change:** 
giphy
@mohitmanuja, @anantprsd5  Please review :)

### CODE REVIEW

**Comment by aditya98ak** [comment]
@mohitmanuja Please review.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -303,6 +310,19 @@ public void onCreate(Bundle savedInstanceState) {
         new initAllPhotos().execute();
         displayData(getIntent().getExtras());
         checkNothing();
+
+        navigationView.setOnNavigationItemSelectedListener(new BottomNavigationView.OnNavigationItemSelectedListener() {
+            @Override
+            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
+                int itemID = item.getItemId();
+                if(itemID==R.id.navigation_home){
+                    startActivity(new Intent(LFMainActivity.this, LFMainActivity.class));
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Don't restart the activity on pressing the home button, just switch to Albums mode if it is in photos mode.

Comment (aditya98ak) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @anantprsd5 Sorry to interrupt, but can you explain why switching to Album Mode, is considered to be a good practice? Sorry for being lame.

Comment (aditya98ak) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @anantprsd5 is that what you want?
Please check this gist :)
https://gist.github.com/aditya98ak/8553e9279f17387aff2e518802be73ea

Comment (anantprsd5) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Why would you want to recreate the same activity when you have an option to manage the contents in that activity. For the hidden folders and the all photos mode and for the photos mode, simply put an if statement and switch to albums mode. Recreating the activity will take much more time rather than just switching to albums mode.

Comment (aditya98ak) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @anantprsd5 I have updated the gist  - https://gist.github.com/aditya98ak/8553e9279f17387aff2e518802be73ea

Everything is working fine now.(I am not recreating activity now)
If this is fine, I'll commit the changes asap :)

Comment (anantprsd5) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Sure. Please commit the changes. Thanks!
