### PR TITLE
Fix #1659-Appropriate message is displayed if search results are null.

### LINKED ISSUE #1659: Modifications required in the search functionality.
**Actual Behaviour**

Issues in the search functionality.

- [ ] Soft-keyboard should automatically pop up when the focus is on search view. 

- [ ] Appropriate message should be displayed if search result is null. 

**Expected Behaviour**

Soft-keyboard should automatically pop up when the search view gets focus.
Proper message should be displayed if the search results are null.

**Steps to reproduce it**

Perform the search operation.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
Fixed #1659 
Changes: Appropriate message is displayed if the results are null on performing the search folder operation.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -1577,6 +1582,12 @@ private void checkNothingFavourites() {
             starImageView.setColorFilter(ContextCompat.getColor(this, R.color.black), PorterDuff.Mode.SRC_ATOP);
     }
 
+    private void checkNoSearchResults(String result){
+        textView.setText(getString(R.string.null_search_result) + " " + '"' + result + '"' );
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: In the string there's already space at the end, do we need two spaces?

Comment (sauravvishal8797) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @abishekvashok Removed the space at the end of the string declaration in strings.xml file. Please review.
