### PR TITLE
Fix #2442 Made navigation drawer visible onResume where ever required.

### LINKED ISSUE #2442: Navigation Bar gets hidden onResume
**Actual Behaviour**

Navigation bar becomes hidden when app enters pause state with albums selected

**Expected Behaviour**

Navigation bar should be visible onResume().

**Steps to reproduce it**

Select albums.
press home button.
reopen app.

**Screenshots of the issue**

ezgif com-video-to-gif

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by angmas1**
Fixed #2442 Made navigation drawer visible onResume where ever required.

Changes: LFMainActivity.java

Screenshots of the change: 

ezgif com-video-to-gif

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -833,11 +833,11 @@ public void onResume() {
         setupUI();
         if (all_photos && !fav_photos) {
             new PrepareAllPhotos(activityContext).execute();
-        }
-        if (!all_photos && fav_photos) {
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Why was this condition removed?

**Comment by abishekvashok** [comment]
Thanks
