### PR TITLE
Fixed #597 and improved UI of ShareActivity

### LINKED ISSUE #597: Buttons overlap in share image activity
**Actual Behaviour**

Buttons overlaps in low resolution screen device(API 19, 480x800 )

**Expected Behaviour**

Shouldn't overlap

**Steps to reproduce it**

In a device with low screen resolution, edit an image and save it. you will enter share image page.

**Screenshots of the issue**

screenshot_2017-06-15-22-25-01

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fix #597 
Changes: Changed the UI completely

screenshot_2017-06-18-12-27-40-728_org fossasia phimpme

### CODE REVIEW

**Comment by mohitmanuja** [comment]
@vinaysajjanapu awesome. This is what exactly I want. 👍

File: app/src/main/java/org/fossasia/phimpme/shareActivity.java [hunk 1]
```diff
@@ -21,109 +29,184 @@
...
+        setSupportActionBar(toolbar);
+
+        setStatusBarColor(getResources().getColor(R.color.md_grey_400));
+
+        parent = findViewById(R.id.share_layout);
+        shareImage = (ImageView)findViewById(R.id.share_image);
+
+        text_caption = (EditText)findViewById(R.id.edittext_share_caption);
+
+        cell00 = findViewById(R.id.cell_00);
```
Comment (the-dagger) [inline app/src/main/java/org/fossasia/phimpme/shareActivity.java]: @vinaysajjanapu We are already using butterknife in the project, so use that instead of conventional finviewbyid calls.

File: app/src/main/java/org/fossasia/phimpme/shareActivity.java [hunk 2]
```diff
@@ -21,109 +29,184 @@
...
-        mImageView.setImageBitmap(myBitmap);
-        mEditText = (EditText) findViewById(R.id.edit_text);
+        try {
+            shareImage.setImageBitmap(BitmapFactory.decodeFile(saveFilePath));
+        }catch (OutOfMemoryError error){
+            Snackbar.make(parent,"Unable to load Image",Snackbar.LENGTH_INDEFINITE)
+                    .setAction("RETRY", new View.OnClickListener() {
+                        @Override
+                        public void onClick(View v) {
+                            Intent share = new Intent(getBaseContext(),shareActivity.class);
```
Comment (the-dagger) [inline app/src/main/java/org/fossasia/phimpme/shareActivity.java]: Refactor the class name to `ShareActivity` please

File: app/src/main/java/org/fossasia/phimpme/shareActivity.java [hunk 3]
```diff
@@ -21,109 +29,184 @@
...
-    FloatingActionButton fab_home;
-    public EditText mEditText;
-    public String filePath;
     public String saveFilePath;
-    public String sendMessage;
     public static final String EXTRA_OUTPUT = "extra_output";
-    public static final String FILE_PATH = "file_path";
     private CallbackManager callbackManager;
-    private LoginManager manager;
+    Toolbar toolbar;
```
Comment (the-dagger) [inline app/src/main/java/org/fossasia/phimpme/shareActivity.java]: Please make all the fields private by default.

**Comment by mohitmanuja** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.phimpme/org.fossasia.phimpme.SharingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setTitleTextColor(int)' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method **'void android.support.v7.widget.Toolbar.setTitleTextColor(int)'** on a null object reference
                                                     at org.fossasia.phimpme.SharingActivity.setupUI(**SharingActivity.java:84**)
                                                     at org.fossasia.phimpme.SharingActivity.onCreate(**SharingActivity.java:78**)
                                                     at android.app.Activity.performCreate(Activity.java:6303)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by vinaysajjanapu** [comment]
@mohitmanuja that was due to kotlins annotationprocessor. please refer this https://github.com/JakeWharton/butterknife/issues/463.
Please update, clean and run again.

**Comment by vinaysajjanapu** [comment]
@the-dagger I made all the changes you requested.

**Comment by vinaysajjanapu** [comment]
@pa1pal I made it like that intentionally. Empty space wont look good in the layout. I used scaletype as centercrop

**Comment by pa1pal** [comment]
@vinaysajjanapu okay. It looks better this way.

**Comment by vinaysajjanapu** [comment]
@the-dagger please approve.

**Comment by mariobehling** [comment]
@the-dagger If issues persist please follow up in following issues/PRs.
