### PR TITLE
Choose image option from other apps

### LINKED ISSUE #599: Choose image from other app is not working
**Actual Behaviour**
The image choosing option is not working.

**Steps to reproduce it**

Open any app. i.e Gmail -> compose mail -> insert file -> choose image -> choose phimpme.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by mohitmanuja**
Fix #599 

Changes:
Choose image option is working properly.
To check open any app. i.e Gmail -> compose mail -> insert file -> choose image -> choose phimpme.

### CODE REVIEW

File: app/src/main/java/vn/mbm/phimp/me/leafpic/activities/SplashScreen.java [hunk 1]
```diff
@@ -65,7 +65,17 @@ public void onCreate(Bundle savedInstanceState) {
...
-            new PrefetchAlbumsData().execute(SP.getBoolean(getString(R.string.preference_auto_update_media), false));
+            PICK_INTENT = getIntent().getAction().equals(Intent.ACTION_GET_CONTENT) || getIntent().getAction().equals(Intent.ACTION_PICK);
+            if (getIntent().getAction().equals(ACTION_OPEN_ALBUM)) {
+                Bundle data = getIntent().getExtras();
+                if (data != null) {
+                    String ab = data.getString("albumPath");
+                    if (ab != null) {
+                        new PrefetchPhotosData().execute();
+                    }
+                } else StringUtils.showToast(getApplicationContext(), "Album not found");
```
Comment (pa1pal) [inline app/src/main/java/vn/mbm/phimp/me/leafpic/activities/SplashScreen.java]: avoid hardcoded string.

Comment (mohitmanuja) [inline app/src/main/java/vn/mbm/phimp/me/leafpic/activities/SplashScreen.java]: done

**Comment by mohitmanuja** [comment]
@pa1pal Done. Please review it again.
