### PR TITLE
Fix #1165 - Display snackbar when media is moved and copied.

### LINKED ISSUE #1165: Toast message when picture is successfully moved and copied
**Actual Behaviour**

No message is given to the user that the move or copy operation was successful.

**Expected Behaviour**

User should be informed about the status of the above operations.

**Steps to reproduce it**

Move or copy any photo.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fix #1165 

Changes: Change to CoordinatorLayout in activity_leafpic.xml so that Snackbar is displayed properly

Screenshots for the change: 
image

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -1549,7 +1552,8 @@ public void onClick(DialogInterface dialog, int id) {
                     @Override
                     public void folderSelected(String path) {
                         swipeRefreshLayout.setRefreshing(true);
-                        if (getAlbum().moveSelectedMedia(getApplicationContext(), path) > 0) {
+                        int number;
```
Comment (vinaysajjanapu) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: try to name variables properly.

**Comment by mayank8318** [comment]
@vinaysajjanapu Sorry I forgot to rename the variable.
