### PR TITLE
Fix #2574 HDR mode dialog issue

### LINKED ISSUE #2574: HDR Dialog shows repeatedly in the camera section
**Actual Behaviour**

HDR dialog shows every time even if we have selected the HDR mode.

**Expected Behaviour**

Dialog should not visible if HDR mode already selected.

**Steps to reproduce it**

Step 1: Select the camera tab.

Step 2: Click on the HDR in the photo mode

Step 3: Dialog appear, click on HDR mode after clicking on OK button in the dialog.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sparrow007**
Fixed #2574 

Changes: [I put the condition that if it's already selected that means it will store in the shared preference then don't go for dialog .]

GIF of the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java [hunk 1]
```diff
@@ -252,14 +252,25 @@ public void onClick(String option) {
...
+							boolean done_dialog = false;
+							if( new_photo_mode == MyApplicationInterface.PhotoMode.HDR && !HDRMessage.equals(sharedPreferences.getString(PreferenceKeys.getPhotoModePreferenceKey(), " "))) {
+								boolean done_hdr_info = sharedPreferences.contains(PreferenceKeys.getHDRInfoPreferenceKey());
+								if( !done_hdr_info ) {
+									showInfoDialog(R.string.photo_mode_hdr, R.string.hdr_info, PreferenceKeys.getHDRInfoPreferenceKey());
+									done_dialog = true;
+								}
+							} else {
+								done_dialog = true;
+							}
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java]: No need for braces in `else` here. It is a single statement.

File: app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java [hunk 2]
```diff
@@ -252,14 +252,24 @@ public void onClick(String option) {
...
     						SharedPreferences.Editor editor = sharedPreferences.edit();
+							final String HDRMessage = "preference_photo_mode_hdr";
+							boolean done_dialog = false;
+							if( new_photo_mode == MyApplicationInterface.PhotoMode.HDR && !HDRMessage.equals(sharedPreferences.getString(PreferenceKeys.getPhotoModePreferenceKey(), " "))) {
+								boolean done_hdr_info = sharedPreferences.contains(PreferenceKeys.getHDRInfoPreferenceKey());
+								if( !done_hdr_info ) {
+									showInfoDialog(R.string.photo_mode_hdr, R.string.hdr_info, PreferenceKeys.getHDRInfoPreferenceKey());
+									done_dialog = true;
+								}
+							} else
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java]:
```suggestion
							} else done_dialog = true;
```

File: app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java [hunk 3]
```diff
@@ -252,14 +252,24 @@ public void onClick(String option) {
...
+							final String HDRMessage = "preference_photo_mode_hdr";
+							boolean done_dialog = false;
+							if( new_photo_mode == MyApplicationInterface.PhotoMode.HDR && !HDRMessage.equals(sharedPreferences.getString(PreferenceKeys.getPhotoModePreferenceKey(), " "))) {
+								boolean done_hdr_info = sharedPreferences.contains(PreferenceKeys.getHDRInfoPreferenceKey());
+								if( !done_hdr_info ) {
+									showInfoDialog(R.string.photo_mode_hdr, R.string.hdr_info, PreferenceKeys.getHDRInfoPreferenceKey());
+									done_dialog = true;
+								}
+							} else 
+								done_dialog = true;
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java]: Shift it to the line above.

Comment (sparrow007) [reply app/src/main/java/org/fossasia/phimpme/opencamera/UI/PopupView.java]: thanks for review , i have update the codes

**Comment by yashk2000** [comment]
@sparrow007 rebase properly please. There are still 2 commits. It should only be 1 after squashing.
