### PR TITLE
fix: Made keyboard enter have same action as ok button on dialog.

### LINKED ISSUE #2600: There are several edit texts where ok has to pressed even after pressing keyboard tick.
**Describe the bug**
Right now there are several text views where ok button jas to be pressed even after pressing keyboard tick.

**Expected behavior**
Pressing the keyboard tick should be an action for ok.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |nokia 7 plus|
|Android Version|Android 9    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2600

Changes: In all dialogs in which there is an edit text, now on pressing the enter button on keyboard, the same action takes place as on pressing ok button.

### CODE REVIEW

**Comment by yashk2000** [comment]
@abishekvashok please review.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -724,6 +761,30 @@ public void onClick(View v) {
                                     }
                                 }
                             });
+
+                    editTextPassword.setOnEditorActionListener(new TextView.OnEditorActionListener() {
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Assign the new EditorListener to a new variable of the same class and just reuse it.

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @abishekvashok could you please help me with this? I am not able to instantiate OnEditorActionListener. 
Also, it would be easier to instantiate and use the same instance of the OnEditorActionListener if the same action was being carried out inside each listener. But here we are carrying out different actions inside different listeners.

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @abishekvashok @sauravvishal8797 can I get some guidance with this issue please?

Comment (abishekvashok) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Oh ok, can you try to use implement multilevel inheritance and derive a class for each of these click listeners (already present) and editor listeners. It's okay if you want me to merge this but the former approach reduces code. Let me know.

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @abishekvashok should I create a Utils class where we can write all the functions and then call them where ever required inside the click and the editor listeners?

Comment (abishekvashok) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Yep

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: @abishekvashok ok, I'll work on it. Thanks for the guidance:)

**Comment by mariobehling** [comment]
@yashk2000 Let's finalize this and resolve conflicts. :-)

**Comment by yashk2000** [comment]
@mariobehling @abishekvashok conflicts resolved.
