### PR TITLE
Fix #1462 - Slideshow bug fixed

### LINKED ISSUE #1462: Slideshow not stopping on click
**Actual Behaviour**
A major bug was that when user enter's the slideshow duration to 1, it will be hard to stop the slideshow by tapping on the screen, and when user enter's the duration to 0, the screen will go black.

**Expected Behaviour**

Slideshow should be stopped on tapping the screen and screen should not go black

**Steps to reproduce it**

1.Enter the slideshow
2.Tap on the screen

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by codedsun**
Fix #1462 Fixed slideshow major bug which I encountered with.

Changes: Added conditions and checks to recover from it.

Screenshots for the change: 
Toast is displayed for slideshow not possible less than 2 sec.

@aditya98ak @mayank8318 @anantprsd5 @mohitmanuja Kindly review!

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -1153,8 +1154,13 @@ public void onClick(DialogInterface dialog, int which) {
                     slideshow=true;
                     int intValue = Integer.parseInt(value);
                     SLIDE_SHOW_INTERVAL = intValue * 1000;
-                    hideSystemUI();
-                    handler.postDelayed(slideShowRunnable, SLIDE_SHOW_INTERVAL);
+                    if(SLIDE_SHOW_INTERVAL > 1000) {
```
Comment (mayank8318) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: shouldn't this be > 2000 if you are saying 2 sec is the minimum duration?

Comment (codedsun) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: @mayank8318 as the user is allowed only to enter integer values hence by going with 2 sec minimum then it should be >=2000, not >2000 as it will not work for 2 sec also.

Comment (codedsun) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Hence I have added for the greater than 1 sec :+1:

**Comment by codedsun** [comment]
@mohitmanuja @anantprsd5 Merge this!

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java (hunk 1 above)
Comment (mayank8318) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: oh yes didn't see that it didn't have '=' there.
