### PR TITLE
Hide copy and move item if no item is selected

### LINKED ISSUE #714: Copy and move to options open window even if no photo is selected
**Actual Behaviour**

From the gallery even if no photo is selected, copy to and move to options open a window to choose a folder. 

**Expected Behaviour**

Check if any image is selected. Show snackbar to select an image 

**Steps to reproduce it**

From LFMainActivity choose: copy to or move to. 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Subhankar29**
Fix #714 

Changes:

- Copy feature is enabled only when a photo is selected. 

- Copy feature disabled from the album view. 

- Move feature is enabled only when an album or a photo is selected

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java [hunk 1]
```diff
@@ -870,9 +871,13 @@ public boolean onPrepareOptionsMenu(final Menu menu) {
 
         togglePrimaryToolbarOptions(menu);
         updateSelectedStuff();
-
-        menu.findItem(R.id.action_copy).setVisible(!all_photos);
-        menu.findItem(R.id.action_move).setVisible(!all_photos);
+        if(getAlbum().getSelectedCount() == 0){
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java]: Can be done in a single line.
```
visible = getAlbum().getSelectedCount()>0;
```

Comment (Subhankar29) [inline app/src/main/java/org/fossasia/phimpme/leafpic/activities/LFMainActivity.java]: done
