### PR TITLE
Fix #1241 add details dialog for album

### LINKED ISSUE #1241: No details dialog for album
**Actual Behaviour**

Currently there is no option to see details of an album

**Expected Behaviour**

There should be a details dialog for albums too similar to the one already present for photos.

**Steps to reproduce it**

Open the app. Long press any album.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fix #1241 

Changes: Added details dialog for album

Screenshots for the change: 
screenshot_20170930-163120
screenshot_20170930-163126

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java [hunk 1]
```diff
@@ -348,6 +351,14 @@ private boolean moveMedia(Context context, String source, String targetDir) {
 	public void setDefaultSortingAscending(Context context, SortingOrder sortingOrder) {
 		settings.changeSortingOrder(context, sortingOrder);
 	}
+    public MediaDetailsMap<String, String> getAlbumDetails(Context context){
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java]: Indentation

Comment (nikit19) [reply app/src/main/java/org/fossasia/phimpme/gallery/data/Album.java]: @anantprsd5  done

**Comment by nikit19** [comment]
updated the pull request by adding two lines in onPrepareOptionsMenu to solve a minor bug.
