### PR TITLE
password edit field hint changed to new password

### LINKED ISSUE #2338: change password edit field issue
**Actual Behaviour**

the edit field hint displays "Password".

**Expected Behaviour**

it should display "New Password"

**Steps to reproduce it**

go to security in settings. navigate to change password. the edit field hints are displayed("Password","Confirm Password").

**Screenshots of the issue**

whatsapp image 2018-12-26 at 14 17 42

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by kk63852**
Fixed #2338 

Changes: the edit field hint of password dialog was changed accordingly for initial setup and change password. 

Screenshots of the change: 
whatsapp image 2018-12-27 at 23 40 16

whatsapp image 2018-12-26 at 15 15 24

### CODE REVIEW

**Comment by yashk2000** [comment]
@kk63852 now when the user will be setting a password initially, then also the hints will be "New Password" and "Confirm New Password".

**Comment by kk63852** [comment]
@yashk2000 its better to have the "New Password" hint, as the user would be setting up the password once only and changing it many times.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java [hunk 1]
```diff
@@ -301,10 +301,12 @@ private void setPasswordDialog() {
 
         editTextPassword.getBackground().mutate().setColorFilter(getTextColor(), PorterDuff.Mode.SRC_ATOP);
         editTextPassword.setTextColor(getTextColor());
+        editTextPassword.setHint(R.string.password);
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SecurityActivity.java]: Can't you set these in xml? It would be much more faster
