### PR TITLE
fix: switch checked/unchecked in accounts section

### LINKED ISSUE #2884: Accounts Activity switch not working properly
**Describe the bug**
Accounts Activity switch not working properly

**To Reproduce**
1. Go to Accounts 
2. Click on OwnCloud 
3. Press back
4. Imgur switch is checked in (or in on state)

Parent Issue: #2877 

**Expected behavior**
This should not happen

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by codedsun**
Fixed #2884 : Fixes switch working in account section

Changes: Handled set checked in adapter

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java [hunk 1]
```diff
@@ -64,6 +64,8 @@ public void onBindViewHolder(ViewHolder holder, int position) {
       holder.signInSignOutSwitch.setChecked(true);
       themeHelper.updateSwitchColor(holder.signInSignOutSwitch, switchAccentColor);
     } else {
+      holder.signInSignOutSwitch.setChecked(false);
+      themeHelper.updateSwitchColor(holder.signInSignOutSwitch,switchBackgroundColor);
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/accounts/AccountAdapter.java]:
```suggestion
      themeHelper.updateSwitchColor(holder.signInSignOutSwitch, switchBackgroundColor);
```

**Comment by codedsun** [comment]
@iamareebjamal merge this!
