### PR TITLE
Fix #2025-Issue in favourites and SingleMediaActivity resolved.

### LINKED ISSUE #2025: Issue in favourites and SiingleMedia Activity.
**Actual Behaviour**

When there is only one photo present in the favorites collection, deleting it via the SingleMedia Activity causes unexpected behavior. 
On adding a photo to favorites via the fav button present in the SingleMediaActivity, the button gets tinted with the accent color to denote the success of operation but when the user slides to another image irrespective of whether or not the image is present in favorites, the fav button gets tinted in the accent color.

**Expected Behaviour**

The app should not show unexpected behavior.

**Steps to reproduce it**

Delete the image via SingleMediaActivity from favorites (only one image should be present in favorites collection).
Add an image to the fav via the SingleMediaActivity then slide to the next image.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
Fixed #2025

Changes: Unexpected behavior resolved for favorites delete operation, the add to favorite button gets tinted only if the image being viewed(via the SingleMediaActivity) is present in the favorites collection.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -365,6 +361,14 @@ public void onPageChanged(int oldPosition, int position) {
                     getAlbum().setCurrentPhotoIndex(position);
                     toolbar.setTitle((position + 1) + " " + getString(R.string.of) + " " + getAlbum().getMedia().size());
                     invalidateOptionsMenu();
+                    if(!favsearch(getAlbum().getMedia(position).getPath())){
+                        bottomMenu.findItem(R.id.action_favourites).getIcon().clearColorFilter();
+                        Log.i("akakakaka", "lopp");
+                        //bottomMenu.findItem(R.id.action_favourites).setIcon(R.drawable.ic_favourite_white_24dp);
+                    }else{
+                        Log.i("akakakakakakakakakaka", "oiuyt");
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Remove this log message.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 2]
```diff
@@ -365,6 +361,14 @@ public void onPageChanged(int oldPosition, int position) {
                     getAlbum().setCurrentPhotoIndex(position);
                     toolbar.setTitle((position + 1) + " " + getString(R.string.of) + " " + getAlbum().getMedia().size());
                     invalidateOptionsMenu();
+                    if(!favsearch(getAlbum().getMedia(position).getPath())){
+                        bottomMenu.findItem(R.id.action_favourites).getIcon().clearColorFilter();
+                        Log.i("akakakaka", "lopp");
+                        //bottomMenu.findItem(R.id.action_favourites).setIcon(R.drawable.ic_favourite_white_24dp);
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Delete this commented line.

**Comment by sauravvishal8797** [comment]
@anantprsd5 Made the suggested changes, please merge this.
