### PR TITLE
Fixes #1344 - AutoHide NavBars, Flag to Fullscreen on User Inactivity

### LINKED ISSUE #1344: Auto Hiding action bars when viewing image
**Actual Behaviour**

When an Image is viewed, action bars are visible for the whole time until user taps on the screen.

**Expected Behaviour**

Action Bars should auto hide after a particular time duration.

**Steps to reproduce it**

View any image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by aditya98ak**
Fix #1344 

Changes: Now, when the user doesn't touch the screen for a while(about 5 seconds), nav-bars, toolbars, will be automatically hidden, and activity will switch to full-screen and will be back to normal by tapping on the screen.

Screenshots for the change: 
giphy 1

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -152,6 +154,18 @@ public void onCreate(Bundle savedInstanceState) {
...
         imageHeight = metrics.heightPixels;
+        handler = new Handler();
+        runnable = new Runnable() {
+            @Override
+            public void run() {
+                View view = getWindow().getDecorView();
+                int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN
+                        |View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
+                        |View.SYSTEM_UI_FLAG_IMMERSIVE;
+                view.setSystemUiVisibility(uiOptions);
```
Comment (nikit19) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: @aditya98ak  you can replace the code inside run() with hideSystemUI()

**Comment by mariobehling** [comment]
Thanks. Please resolve conflicts.

**Comment by aditya98ak** [comment]
@mariobehling Conflicts Resolved.
