### PR TITLE
Fix for issue#2359: Made the entire text toggleable.

### LINKED ISSUE #2359: tapping on switch to turn on/off
**Actual Behaviour**
Tapping on switch to turn on/off rather tapping on list(linearlayout) to turn on/off

**Expected Behaviour**
Tapping on list to turn on/off 

**Screenshots of the issue**

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2359 

Changes: In settings and security settings, now the entire text can be tapped to toggle a setting on or off.

GIF of the change: 

ezgif com-video-to-gif 8

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java [hunk 1]
```diff
@@ -265,6 +317,19 @@ public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
...
+        colornavBar.setOnClickListener(new View.OnClickListener() {
+            @Override
+            public void onClick(View v) {
+                boolean no = swNavBar.isChecked();
+                if(no){
+                    swNavBar.setChecked(false);
+                }else {
+                    swNavBar.setChecked(true);
+                }
+
```
Comment (GOVINDDIXIT) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java]: Extra

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java [hunk 2]
```diff
@@ -251,6 +290,19 @@ public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
...
+        statusBar.setOnClickListener(new View.OnClickListener() {
+            @Override
+            public void onClick(View v) {
+                boolean no = swStatusBar.isChecked();
+                if(no){
+                    swStatusBar.setChecked(false);
+                }else{
+                    swStatusBar.setChecked(true);
+                }
+
```
Comment (GOVINDDIXIT) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java]: Extra

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java [hunk 3]
```diff
@@ -239,6 +264,20 @@ public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
...
+        maxLuminosity.setOnClickListener(new View.OnClickListener() {
+            @Override
+            public void onClick(View v) {
+                boolean no = swMaxLuminosity.isChecked();
+                if(no){
+                    swMaxLuminosity.setChecked(false);
+                }else{
+                    swMaxLuminosity.setChecked(true);
+                }
+
```
Comment (GOVINDDIXIT) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SettingsActivity.java]: Extra
