### PR TITLE
fix: outOfMemory Exception. Removed the last edited action added latest action in list

### LINKED ISSUE #640: Handle undo in editor when outofmemory exception is caught
**Actual Behaviour**

There is no proper implementation after outofmemory exception is caught.

**Expected Behaviour**

Release memory somehow by either removing previous oldest tracking image and add current tracking image to end.

**Steps to reproduce it**

Open image in editor. keep on editing multiple times ( may be 15) and press undo.

**Would you like to work on the issue?**

I like to. But if anyone wants to work on it they can.

### PR DESCRIPTION
**Pull request by pa1pal**
Fix  #640 

Changes: 
- [x]  Removed the last edited action and added the latest action in the list
- [x]  change the visibility of undo button from invisible to gone to fix the UI of button
- [x]  Change the PR templace

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java [hunk 1]
```diff
@@ -355,10 +355,17 @@ public void changeMainBitmap(Bitmap newBit) {
...
+
             bitmapsForUndo.add(mainBitmap.copy(mainBitmap.getConfig(),true));
         }catch (OutOfMemoryError error){
-            //Snackbar.make(getWindow().getDecorView().getRootView(),"Out of Memory. steps = " + bitmapsForUndo.size(),Snackbar.LENGTH_LONG).show();
-
+            /**
+             * When outOfMemory exception throws then to make space, remove the last edited step
+             * from list and added the new operation in the end.
+             */
+            bitmapsForUndo.remove(0);
```
Comment (vinaysajjanapu) [inline app/src/main/java/org/fossasia/phimpme/editor/editimage/EditImageActivity.java]: remove the bitmap of index 1 from the list. 
because when we keep on undoing, it would be better if we end up with the original image rather than some randomly edited image.

I am not sure whether only just removing bitmap from the list would clear memory. I think you should call bitmap.recycle before removing that bitmap from the list.
