### PR TITLE
fix:Snackbar placement in the view above to bottomNavigationView

### LINKED ISSUE #955: Snackbar placement is wrong in app
**Actual Behaviour**

The view element in most of places in the code is not placed correctly, which actually led it to cover the bottomNavigationView for the time it visible.

**Expected Behaviour**

Fixing the view part of wrong placed snackbar

**Screenshots of the issue**

screen shot 2017-08-04 at 11 56 13 pm

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by pa1pal**
Fix #955 

Changes: Put the recycler view in another coordinator view layout. Pass the new view in the snackbar method.

Screenshots for the change: 
screen shot 2017-08-06 at 12 39 16 am

### CODE REVIEW

File: app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/HomeScreenTest.java [hunk 1]
```diff
@@ -129,7 +129,7 @@ public void describeTo(Description description) {
             @Override
             public boolean matchesSafely(View view) {
                 ViewParent parent = view.getParent();
-                return parent instanceof ViewGroup && parentMatcher.matches(parent)
+                return parent instaznceof ViewGroup && parentMatcher.matches(parent)
```
Comment (vinaysajjanapu) [inline app/src/androidTest/java/org/fossasia/phimpme/leafpic/activities/HomeScreenTest.java]: travis error here
