### PR TITLE
Fix #1446-Appropriate message is displayed for description and Exif a…

### LINKED ISSUE #1446: Appropriate text should be displayed in the description attribute of the Image details dialog if no description is added.
**Actual Behaviour**

Nothing is displayed in the description attribute of the Image details dialog if no description for the image is added.

**Expected Behaviour**

Appropriate text should be displayed.

**Steps to reproduce it**

Click on details for any image.

**Screenshots of the issue**

screenshot_2017-10-31-01-03-10-215_org fossasia phimpme

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sauravvishal8797**
…ttributes

Fix #1446 

Changes: Appropriate message is displayed for Exif and description attributes.

Screenshots for the change: 
screenshot_2017-10-31-02-46-56-224_org fossasia phimpme

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -781,9 +781,21 @@ public void onClick(View v) {
...
-                        imgDesc.setText(mediaDetailsMap.get("Description"));
-                        imgExif.setText(mediaDetailsMap.get("EXIF"));
-                        imgLocation.setText(mediaDetailsMap.get("Location").toString());
+                         if(mediaDetailsMap.get("Description") == null) {
+                             imgDesc.setText("No description added.");
+                         } else{
+                             imgDesc.setText(mediaDetailsMap.get("Description"));
+                         }
+                         if(mediaDetailsMap.get("EXIF") == null){
+                             imgExif.setText("No data found");
```
Comment (mohitmanuja) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Please don't use hardcoded strings.
