### PR TITLE
Fix #1701-Photos can be stamped with location address.

### LINKED ISSUE #1701: GPS photo stamp modification.
**Actual Behaviour**

Photos can be stamped with location coordinates only, no option to stamp photos with location address.

**Expected Behaviour**

Option to stamp photos with location address should be there.

**Steps to reproduce it**

Go to the camera settings, in the photo settings enable the stamp photo option then go to the GPS stamp section. Click a photo to see the stamp.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
Fixed #1701

Changes: Added option to stamp photos with location address in the photo stamp settings.
Screenshots for the change: 
img_20180129_230200

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/opencamera/Camera/LocationSupplier.java [hunk 1]
```diff
@@ -219,6 +225,19 @@ public boolean hasLocationListeners() {
...
+		Geocoder geocoder = new Geocoder(context, Locale.getDefault());
+		try {
+			List<Address> addressList = geocoder.getFromLocation(location.getLatitude(), location.getLongitude(), 1);
+			address = addressList.get(0);
+		} catch (IOException e) {
+			e.printStackTrace();
+		}
+		return address;
+	}
+
```
Comment (mayank8318) [inline app/src/main/java/org/fossasia/phimpme/opencamera/Camera/LocationSupplier.java]: Please avoid extra lines.

Comment (sauravvishal8797) [reply app/src/main/java/org/fossasia/phimpme/opencamera/Camera/LocationSupplier.java]: @mayank8318 Done. Please check.
