### PR TITLE
Login only from Accounts Activity for Facebook and Flickr

### LINKED ISSUE #879: Login only from Accounts Activity for Facebook and Flickr
**Actual Behaviour**

Users can log in from Accounts Activity and from Sharing Activity

**Expected Behaviour**

To login only from Accounts activity for Facebook and Flickr. 

**Steps to reproduce it**

sharingActivity->Facebook
sharingActivity->Flickr

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by Subhankar29**
Fix #879 

Changes: 

- Checking if logged in to Facebook and Flickr in SharingActivity and showing appropriate snackbar. 

- Added snackbar after uploading the image on Facebook.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java [hunk 1]
```diff
@@ -448,24 +451,28 @@ protected void onPostExecute(Void result) {
...
-            is = getContentResolver().openInputStream(Uri.fromFile(file));
-        } catch (Exception e) {
-            e.printStackTrace();
-        }
-        if (is != null) {
-            FlickrHelper f = FlickrHelper.getInstance();
-            f.setInputStream(is);
-            f.setFilename(file.getName());
+        if (Utils.checkAlreadyExist(FLICKR)) {
+            Intent intent = new Intent(getApplicationContext(),
```
Comment (mohitmanuja) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: @Shubhankar please remove for  Flickr code because I am cleaning code for Flickr. Please send PR by today. In that I am doind this in different way.

**Comment by Subhankar29** [comment]
@mohitmanuja Done please review.
