### PR TITLE
Made Caption Dialog box with material design 

### LINKED ISSUE #950: Make Add caption Dialog box Material Design
**Actual Behaviour**

The current add caption design is plain and simple with no heading. 

**Expected Behaviour**

To maintain the uniformity of the application and since most of the dialog box is material,  make the ADD caption dialog box with material design also.

**Steps to reproduce it**
SharingActivity->Caption

**Screenshots of the issue**

screenshot_2017-08-04-10-11-31-846

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by Subhankar29**
Fix #950 

Changes: To maintain the uniformity of the application. I have added Caption dialog box with material design. 

Screenshots for the change: 
screenshot_20170804-100510

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java [hunk 1]
```diff
@@ -575,15 +574,12 @@ protected void onPostExecute(Void result) {
...
 
     private void openCaptionDialogBox() {
-        AlertDialog.Builder captionDialogBuilder = new AlertDialog.Builder(SharingActivity.this, getDialogStyle());
-        final EditText captionEditText = getCaptionDialog(this, captionDialogBuilder);
-        if (caption != null) {
-            captionEditText.setText(caption);
-            captionEditText.setSelection(caption.length());
-        }
+        final AlertDialog.Builder captionDialogBuilder = new AlertDialog.Builder(SharingActivity.this, getDialogStyle());
+        final EditText captionEditText = new EditText(getApplicationContext());
```
Comment (mohitmanuja) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: Add here

if (caption != null) {		
          captionEditText.setText(caption);		
          captionEditText.setSelection(caption.length());		
      }

Comment (Subhankar29) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: @mohitmanuja Done.
