### PR TITLE
Fix #1259 only one date is displayed now

### LINKED ISSUE #1259: Two dates in details dialog
**Actual Behaviour**

If we open the details dialog of any photo taken by the camera we see two dates are there with different times.
"Date taken" is incorrect

**Expected Behaviour**

Only one date should be there. "Date taken" should be removed as it is incorrect and will only confuse the user.

**Steps to reproduce it**

Open the app. click on any photo.Open the details dialog.

**Screenshots of the issue**

screenshot_20171002-215840

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fix #1259 

Changes:Only one date is displayed now

Screenshots for the change: 
screenshot_20171003-000308

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/data/Media.java [hunk 1]
```diff
@@ -184,8 +184,8 @@ public GeoLocation getGeoLocation()  {
         details.put(context.getString(R.string.size), StringUtils.humanReadableByteCount(size, true));
         details.put(context.getString(R.string.date), SimpleDateFormat.getDateTimeInstance().format(new Date(getDateModified())));
         details.put(context.getString(R.string.orientation), getOrientation()+""+(char) 0x00B0);
-        if (metadata.getDateOriginal() != null)
-            details.put(context.getString(R.string.date_taken), SimpleDateFormat.getDateTimeInstance().format(metadata.getDateOriginal()));
+        //if (metadata.getDateOriginal() != null)
+            //details.put(context.getString(R.string.date_taken), SimpleDateFormat.getDateTimeInstance().format(metadata.getDateOriginal()));
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/data/Media.java]: Remove the codes, don't comment it.

Comment (nikit19) [reply app/src/main/java/org/fossasia/phimpme/gallery/data/Media.java]: ok done
