### PR TITLE
Fixed #2226 Actionbar hidden on second screen when scrolls down in first screen 

### LINKED ISSUE #2226: Actionbar hidden on second screen when scrolls down in first screen
**Actual Behaviour**

when scroll down in album section action bar will  hidden then tap on the album and go to all the image of tapped album where action bar already hidden without scrolling.

**Expected Behaviour**

It should not hidden first, it should hide after scrolling the images.

**Steps to reproduce it**

Step 1. Scrolls down in album section when action will hidden.

Step 2. At that moment click on the album, it will open new page where all images of that album appears.

Step At first hidden action bar is still hidden

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sparrow007**
Fixed #2226 

Changes: [Added a new method for showing the toolbar when it goes from album to photos screen]

GIF of the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -715,6 +716,14 @@ private void clearOverlay() {
                 | AppBarLayout.LayoutParams.SCROLL_FLAG_ENTER_ALWAYS);
     }
 
+    //To show the appbar
+    private void showAppBar() {
+        if (toolbar.getParent() instanceof AppBarLayout) {
+            ((AppBarLayout)toolbar.getParent()).setExpanded(true, true);
+        }
+
```
Comment (codepoet2017390) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Please remove this extra space and also i think there is no need of the comment as the method name is very much self-explanatory

**Comment by abishekvashok** [comment]
Thanks
