### PR TITLE
fix: Added snackbars when image is deleted from SingleMediaActivity.

### LINKED ISSUE #2590: snackbar should be displayed if image is deleted permanently
**Describe the bug**

no message is displayed if image is deleted permanently.
**To Reproduce**

1. select few images.
2. Click on 'delete'
3. uncheck the checkbox which ask the item to move it to trashbin.
4. no message is displayed if the images are deleted permanently.

**Expected behavior**

a snackbar should be displayed.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2590 

Changes: If an image is deleted or moved to trashbin from the SingleMediaActivity, a snackbar is shown. Removed the `showsnackbar` method as we need different messages when albums and images are deleted.

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic @iamareebjamal @abishekvashok @mariobehling please review.

**Comment by yashk2000** [comment]
@iamareebjamal @abishekvashok @mariobehling please review.

**Comment by mariobehling** [comment]
Please provide a screenshot and test apk.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -2190,22 +2190,26 @@ protected void onPostExecute(Boolean result) {
                 getAlbums().clearSelectedAlbums();
                 mDrawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED);
                 albumsAdapter.notifyDataSetChanged();
+                Snackbar snackbar =
+                    SnackBarHandler.show(
+                        mDrawerLayout,
```
Comment (abishekvashok) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: You could make it a function and pass the string as a parameter

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: SnackbarHandler is the function created for this purpose.

**Comment by yashk2000** [comment]
@mariobehling screenshot: All snackbars made are of the same type, for albums, different message.

screencap

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java (hunk 1 above)
Comment (abishekvashok) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: Reuse the statement pls, it's being used many times.

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: But that is how snackbars are created throughout the app. In some cases, the SnackbarHandler functions are used directly, otherwise a snackbar is returned from the class which is stored and then displayed. It has to be this way in order to adjust for the layout and height of the bottom bar.

If there is any other way, could you please suggest?
