### PR TITLE
Fix #1565-SD card icon displayed for albums present in the external s…

### LINKED ISSUE #1565: Modifications in albums adapter item view.
**Actual Behaviour**

In the item view for albums adapter, album name and album media count are displayed.

**Expected Behaviour**

Along with the album name and media count an external storage icon should be displayed for the albums present in the external storage to easily differentiate between the internal and external storage albums.

**Steps to reproduce it**

Open the LFmainactivity in albums mode.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
…torage.

Fix #1565 

Changes: SD card icon displayed along with album name and media count for albums present in the external storage.

Screenshots for the change: 
screenshot_2017-12-30-04-30-48-836_org fossasia phimpme

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java [hunk 1]
```diff
@@ -75,6 +76,12 @@ public void onBindViewHolder(final AlbumsAdapter.ViewHolder holder, int position
         Album a = SharedMediaActivity.getAlbums().dispAlbums.get(position);
         Media f = a.getCoverAlbum();
 
+        if(a.getPath().contains(Environment.getExternalStorageDirectory().getPath())){
+            holder.storage.setVisibility(View.INVISIBLE);
```
Comment (sridharjajoo) [inline app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java]: Proper formatting should be done for the if statement. Something like the following ,as it is been followed else where as well. 
if( ) {
}

Comment (sridharjajoo) [inline app/src/main/java/org/fossasia/phimpme/gallery/adapters/AlbumsAdapter.java]: Proper formatting should be done for the if statement. Something like the following ,as it is been followed else where as well.
if( ) {
}
