### PR TITLE
Fixes #1228 create new folder will not make folders with no name

### LINKED ISSUE #1228: Create new folder makes folders with no name
**Actual Behaviour**

When we click on create new folder and press the spacebar it creates a folder with no name

**Expected Behaviour**

Folders with no name shouldn't be created. There should be a Toast message instead of creating folders with no name.
**Steps to reproduce it**

Long press any album or photo.
Then select move to or copy to.
Click on the icon on  top of the dialog.
Then click on create new folder.
Press the spacebar and click on OK

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fix #1228 

Changes: Folders with no name or folders which already exist will not be created instead the user will get a toast message
Screenshots for the change: 
ezgif com-video-to-gif 8

### CODE REVIEW

**Comment by nikit19** [comment]
@nb2998  okay I'll update the PR to check that too

**Comment by nikit19** [comment]
ezgif com-video-to-gif 9

File: app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java [hunk 1]
```diff
@@ -128,9 +129,24 @@ public void onClick(View view) {
...
+                  filePosition++;
+                  if (editText.getText().toString().equals(f.getName()))
+                      check=0;
+              }
+              if(!editText.getText().toString().trim().isEmpty() && check!=0) {
 			File folderPath = new File(currentFolderPath.getText().toString() + File.separator + editText.getText().toString());
 			if (folderPath.mkdir()) displayContentFolder(folderPath);
+              }
+              else if(check==0)
+                  Toast.makeText(getContext(),R.string.folder_name_exists,Toast.LENGTH_SHORT).show();
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java]: Use a Snackbar instead

Comment (nikit19) [reply app/src/main/java/org/fossasia/phimpme/gallery/SelectAlbumBottomSheet.java]: @anantprsd5 I think since this is a dialog a toast message would be better because when I use a snackbar it is not visible till I move the dialog to full screen. What do you think?
ezgif com-video-to-gif 10
