### PR TITLE
Fix #2596 text highlight visible in caption dialog in dark amoled theme

### LINKED ISSUE #2596: in share Image, Caption Text Highlight not visible in Dark AMOLED theme
**Describe the bug**

When try to edit the already given caption in share image, with dark AMOLED theme, text highlight is not visible.

**To Reproduce**
1. Change theme to Dark AMOLED
2. Select and image and click on share icon
3. Add Some Caption and press 'ok'
4. Again click on caption 

**Expected behavior**

Caption text should have highlight

**Screenshots**

screenshot_20190220-013540

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus|
|Android Version| Oreo 8.1  |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by neel1998**
Fixed #2596 
Changes: highlight visible in caption dialog

Screenshots of the change: 
screenshot_20190222-171040

### CODE REVIEW

**Comment by neel1998** [comment]
@yashk2000  please review. Same as the previous :P

File: app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java [hunk 1]
```diff
@@ -772,7 +772,9 @@ private void openCaptionDialogBox() {
         captionEditText.setHint(R.string.description_hint);
         captionEditText.setHintTextColor(ContextCompat.getColor(this,R.color.grey));
         captionEditText.setSelectAllOnFocus(true);
-        captionEditText.setHighlightColor(ContextCompat.getColor(getApplicationContext(), R.color.cardview_shadow_start_color));
+        if(getBaseTheme() == ThemeHelper.DARK_THEME || getBaseTheme() == ThemeHelper.AMOLED_THEME){
+            captionEditText.setHighlightColor(ContextCompat.getColor(getApplicationContext(), R.color.accent_grey));
```
Comment (yashk2000) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: Set the captionEditText color also as black so that it is visible on highlighting.

Comment (neel1998) [reply app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: It is visible right now as well. I think we don't need to set it to black. Further when the user enters the caption for the first time, There is no highlight so black fonts are not visible on black background. Try running this code change once, i think it is working as expected

Comment (yashk2000) [reply app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: ok then.
