### PR TITLE
Fix #1379 Ask for sd Card permission for deletion

### LINKED ISSUE #1379: Asking For SD-Card write permission, for deleting image from singleMediaActivity.
**Actual Behaviour**

Deleting an image from sd card is not working from singleMediaActivity if permissions are not granted, so it should ask for permissions

**Expected Behaviour**

It should ask for permission if not granted.

**Steps to reproduce it**

Do not grant permission for sd card write access, and then open an image, click on delete from the bottom nav bar, it will not delete.

**Screenshots of the issue**

giphy 1

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by aditya98ak**
Fix #1379 

Changes: Now, if permission is not granted, it is asked, and thus delete is working fine now.

Screenshots for the change: 

giphy 2

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java [hunk 1]
```diff
@@ -447,7 +454,23 @@ private void displayAlbums(boolean reload) {
 
     private void deleteCurrentMedia() {
         if (!allPhotoMode) {
-            getAlbum().deleteCurrentMedia(getApplicationContext());
+            boolean success = getAlbum().deleteCurrentMedia(getApplicationContext());
+            if(!success){
+
+                final AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(SingleMediaActivity.this, getDialogStyle());
+
```
Comment (mayank8318) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/SingleMediaActivity.java]: Try to avoid unnecessary line breaks and keep the code compact.

**Comment by aditya98ak** [comment]
@mayank8318  Sorry for that, I was trying to do that, Will double check next time. :+1: , Thanks!
btw, any suggestions for this PR?

**Comment by mayank8318** [comment]
@aditya98ak Looks good otherwise.
