### PR TITLE
Fix #1212 - Add appbar animation

### LINKED ISSUE #1212: Add animation when toolbar veiws chanegs (eg when an item is selected)
**Actual Behaviour**

There is no animation while changing views visibility in toolbar

**Expected Behaviour**

Some Animation should be there...

**Steps to reproduce it**

Open app, select any album., views of toolbar changes suddenly without any animation.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by aditya98ak**
Fix #1212

Changes: Animation to app bar added, now when the user selects a photo/album, app bar is animated.

Screenshots for the change: 
giphy

@vinaysajjanapu @anantprsd5 @mohitmanuja 
Please review.

### CODE REVIEW

**Comment by aditya98ak** [comment]
@anantprsd5 @mohitmanuja @vinaysajjanapu please review, thanks.

File: app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java [hunk 1]
```diff
@@ -141,6 +144,10 @@
     private View.OnLongClickListener photosOnLongClickListener = new View.OnLongClickListener() {
         @Override
         public boolean onLongClick(View v) {
+            if(checkForReveal ==0) {
+                enterReveal();
+                checkForReveal++;
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/gallery/activities/LFMainActivity.java]: It would be better if checkForReveal variable is of Boolean type.

**Comment by aditya98ak** [comment]
@anantprsd5 checkForReveal is now boolean.
