### PR TITLE
Changed edited image format to that of input image

### LINKED ISSUE #993: Editing a transparent png is returning a normal jpg
**Actual Behaviour**

Transparacy is not maintained for a png image

**Expected Behaviour**

If an image has an alpha channel, it should be maintained.

**Steps to reproduce it**

Edit a transparent png image in editor. 

**Would you like to work on the issue?**

yes.

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fix #993 
Changes: 
found the extension from the path of the image and created the output file with that extension

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/editor/FileUtils.java [hunk 1]
```diff
@@ -43,12 +43,26 @@ public static File createFolders() {
...
-	public static File genEditFile(){
+	public static File genEditFile(String extension){
 		return FileUtils.getEmptyFile("phimpme"
-				+ System.currentTimeMillis() + ".jpg");
+				+ System.currentTimeMillis() + extension);
 	}
 
-	public static File getEmptyFile(String name) {
+	public static String getExtension(String path){
+		String lc = path.toLowerCase();
```
Comment (anantprsd5) [inline app/src/main/java/org/fossasia/phimpme/editor/FileUtils.java]: It can be done like this
return lc.substring(lc.lastIndexOf("."))

Comment (vinaysajjanapu) [inline app/src/main/java/org/fossasia/phimpme/editor/FileUtils.java]: Sure @anantprsd5.
Made changes. please review. thanks.
