### PR TITLE
Cleaned Twitter upload code and fixed first time error

### LINKED ISSUE #807: Error on first time on sharing on twitter
**Actual Behaviour**

Some error occurs when clicking first time on twitter from sharing activity and again showing authorising twitter.

**Expected Behaviour**

It shouldn't occur.

**Steps to reproduce it**

First, Clear app data.
Setup twitter account from the accounts section. Then go to share activity and click on twitter.

**Screenshots of the issue**

**Would you like to work on the issue?**

@Subhankar29 @pa1pal If you want to work on this you can.

### PR DESCRIPTION
**Pull request by mohitmanuja**
Fix #807 
Changes:

Fixed twitter first-time uploading issue.
Removed shared prefs to store key and secret. Using realm like other accounts.

### CODE REVIEW

File: app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java [hunk 1]
```diff
@@ -588,24 +588,26 @@ public void onFailure(PDKException exception) {
...
+                                finalBmp = resource;
+                                new PostToTwitterAsync().execute();
 
-                        }
-                    });
-        } else {
+                            }
+                        });
+            }else {
+                Toast.makeText(this, getString(R.string.sign_from_account), Toast.LENGTH_SHORT).show();            }
```
Comment (pa1pal) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: Use Snackbar

Comment (mohitmanuja) [inline app/src/main/java/org/fossasia/phimpme/share/SharingActivity.java]: @pa1pal Yeah sure.

**Comment by vinaysajjanapu** [comment]
@the-dagger Can to you please check this. Travis Build is not even reaching upto app:compile stage.
Gradle is building properly on our local machines and the app is working fine.
